[package]
name = "reth-rpc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = """
Reth RPC implementation
"""
[dependencies]
# reth
reth-interfaces = { path = "../../interfaces" }
reth-primitives = { path = "../../primitives" }
reth-rpc-api = { path = "../rpc-api" }
reth-rpc-types = { path = "../rpc-types" }
reth-provider = { path = "../../storage/provider"}
reth-transaction-pool = { path = "../../transaction-pool" }

# rpc
jsonrpsee = { version = "0.16" }

# misc
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
hex = "0.4"
