[workspace]
members = [
    "bin/reth",
    "crate-template",
    "crates/common/rlp",
    "crates/common/rlp-derive",
    "crates/consensus",
    "crates/executor",
    "crates/interfaces",
    "crates/net/p2p",
    "crates/net/ecies",
    "crates/net/eth-wire",
    "crates/net/discv4",
    "crates/net/network",
    "crates/net/ipc",
    "crates/net/rpc",
    "crates/net/rpc-api",
    "crates/net/rpc-types",
    "crates/net/headers-downloaders",
    "crates/net/bodies-downloaders",
    "crates/primitives",
    "crates/stages",
    "crates/storage/codecs",
    "crates/storage/db",
    "crates/storage/libmdbx-rs",
    "crates/storage/libmdbx-rs/mdbx-sys",
    "crates/storage/provider",
    "crates/tracing",
    "crates/transaction-pool",
]
default-members = ["bin/reth"]
