[package]
name = "reth-executor"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"

[dependencies]
# reth 
reth-primitives = { path = "../primitives" }
reth-interfaces = { path = "../interfaces" }
reth-rlp = { path = "../common/rlp" }
reth-db = {path = "../storage/db"}
reth-provider = {path = "../storage/provider"}
reth-consensus = { path = "../consensus" }

revm = "2.3"
# remove from reth and reexport from revm
hashbrown = "0.13"

# common
async-trait = "0.1.57"
thiserror = "1.0.37"
eyre = "0.6.8"
auto_impl = "1.0"

triehash = "0.8"
# See to replace hashers to simplify libraries
plain_hasher = "0.2"
hash-db = "0.15"
# todo replace with faster rlp impl
rlp = { version = "0.5", default-features = false }
# replace with tiny-keccak (it is faster hasher)
sha3 = { version = "0.10", default-features = false }


[dev-dependencies]
reth-db = { path = "../storage/db", features = ["test-utils"]}